server:
  port: 8081

gcloud:
  bigquery:
    translation:
      projectId: 'root-stock-378622'
      location: 'us'
      inPath: 'axp-lumid-mdm2'
      srcFilePath: 'temp/hive_bq_conversion_src'
      outPath: 'axp-lumid-mdm2'
      destFilePath: 'temp/hive_bq_conversion'
      workflowName: 'testWorkflow'
      taskName: 'testTask'

logging:
  level:
    root: info