server:
  port: 8081

gcp.pubsub.subscription: mdm-internal-sub

spring:
  cloud:
    gcp:
      pubsub:
        publisher:
#          endpoint: pubsub-dev.p.googleapis.com:443
          endpoint: pubsub.googleapis.com:443
        subscription:
          mdm-internal-sub:
            pull-endpoint: pubsub-dev.p.googleapis.com:443

logging:
  level:
    root: debug